"use client";
import Image from "next/image";
import {FlaskConical,Gift,History,Play,RotateCcw,Sparkles} from "lucide-react";
import {useState} from "react";
import {toast} from "sonner";
import {Badge,Button,Card,Progress} from "@/components/ui";
import {PageHeader,SectionTitle} from "./common";
import {useLab} from "@/components/providers";
import {enhancementConfig} from "@/lib/mock/data";
import {number} from "@/lib/utils";
export function Enhancement(){
 const lab=useLab(),[busy,setBusy]=useState(false),[result,setResult]=useState<string|null>(null),config=enhancementConfig.levels[Math.min(lab.level,29)];
 const run=async()=>{setBusy(true);setResult(null);try{const r=await lab.enhance();setResult(r.success?"강화 성공! Lv."+r.after:"아쉽게 실패했어요. 포인트를 모아 다시 도전하세요.");toast[r.success?"success":"error"](r.success?"강화 실험 성공!":"강화 실험 실패")}catch(e){toast.error(e instanceof Error?e.message:"처리하지 못했습니다.")}finally{setBusy(false)}};
 return <><PageHeader title="포인트 강화실" description="포인트를 사용해 연구 레벨을 높이고 단계별 보상을 받으세요." actions={<Button variant="ghost" onClick={lab.resetDemo}><RotateCcw size={15}/>데모 초기화</Button>}/><div className="enhancement-hero"><div><span>POINT EXPERIMENT</span><h2>오늘의 강화 실험을<br/>시작해 볼까요?</h2><p>결과는 서버에서 계산되며 같은 요청은 한 번만 처리됩니다.</p></div><Image src="/assets/naerumi/naerumi-main.png" alt="내루미 연구원" width={220} height={220} priority/></div><div className="enhancement-layout"><Card className="enhance-machine"><div className="level-orb"><FlaskConical/><small>CURRENT LEVEL</small><strong>Lv.{lab.level}</strong><span>연속 성공 {lab.streak}회</span></div><div className="machine-info"><div><span>보유 포인트</span><b>{number(lab.points)}P</b></div><div><span>필요 포인트</span><b>{number(config.cost)}P</b></div><div><span>성공 확률</span><b>{config.probability.toFixed(1)}%</b></div></div><Progress value={config.probability}/>{result&&<p className="result-message"><Sparkles size={18}/>{result}</p>}<Button className="enhance-button" disabled={busy||lab.points<config.cost||lab.level>=30} onClick={run}><Play size={18}/>{busy?"실험 결과 분석 중...":"포인트 강화하기"}</Button><small>일일 최대 {enhancementConfig.dailyLimit}회 · 실패 시 레벨 유지</small></Card><Card><SectionTitle title="단계별 연구 보상" sub="달성한 레벨 보상을 받아 보세요."/><div className="reward-list">{[5,10,15,20,25,30].map(l=>{const reward=l*2500,done=lab.claimedRewards.includes(l);return <div key={l} className={lab.level>=l?"ready":""}><Gift/><span><b>Lv.{l} 달성</b><small>{number(reward)}P 연구 보상</small></span><Button disabled={lab.level<l||done} onClick={()=>lab.redeem(l,reward)}>{done?"수령 완료":lab.level>=l?"받기":"잠김"}</Button></div>})}</div></Card></div><Card><SectionTitle title="최근 강화 기록" sub="확률과 결과를 투명하게 기록합니다." action={<History size={18}/>}/><div className="table-wrap"><table><thead><tr><th>시간</th><th>레벨</th><th>사용 포인트</th><th>적용 확률</th><th>결과</th></tr></thead><tbody>{lab.attempts.slice(0,10).map(a=><tr key={a.id}><td>{a.createdAt}</td><td>Lv.{a.levelBefore} → Lv.{a.levelAfter}</td><td>{number(a.cost)}P</td><td>{a.probability.toFixed(1)}%</td><td><Badge tone={a.result==="success"?"green":"red"}>{a.result==="success"?"성공":"실패"}</Badge></td></tr>)}</tbody></table></div></Card></>
}
