"use client";
import {Bell,Boxes,CheckCircle2,Download,MessageSquare,Plus,RefreshCw,Save,Send,Settings,Store as StoreIcon} from "lucide-react";
import {useState} from "react";
import {toast} from "sonner";
import {Badge,Button,Card,Progress} from "@/components/ui";
import {DonutChart,SimpleBarChart} from "@/components/charts";
import {PageHeader,SectionTitle} from "./common";
import {useLab} from "@/components/providers";
import {salesTrend,stores} from "@/lib/mock/data";
import {downloadCsv,won} from "@/lib/utils";
export function Stores(){return <><PageHeader title="지점 연구소 관리" description="전체 지점의 연동, 매출, 배송 현황을 확인합니다." actions={<Button onClick={()=>toast.success("새 지점 등록 안내를 열었습니다.")}><Plus size={16}/>지점 등록</Button>}/><div className="store-grid">{stores.map(s=><Card key={s.id}><div className="store-card-head"><span><StoreIcon/></span><Badge tone={s.status==="연동 정상"?"green":s.status==="경고"?"amber":"red"}>{s.status}</Badge></div><h3>{s.name}</h3><p>{s.address}</p><div className="store-metrics"><div><small>오늘 매출</small><b>{won(s.todaySales)}</b></div><div><small>배송 대기</small><b>{s.waitingShipments}건</b></div></div><footer><span>{s.manager} · {s.phone}</span><small>동기화 {s.lastSyncedAt}</small></footer></Card>)}</div></>}
export function Catalog(){const lab=useLab();return <><PageHeader title="상품·쿠지 관리" description="쿠지판과 등급별 상품 구성을 통합 관리합니다." actions={<Button><Plus size={16}/>상품 등록</Button>}/><Card><SectionTitle title="통합 상품 카탈로그" sub={lab.boards.length+"개 쿠지판"}/><div className="catalog-grid">{lab.boards.map((b,i)=><article key={b.id}><div className={"catalog-thumb t"+i}><Boxes/><span>{b.category}</span></div><Badge tone={b.status==="진행 중"?"green":"gray"}>{b.status}</Badge><h3>{b.title}</h3><p>{b.code}</p><div><span>{won(b.ticketPrice)}</span><b>{b.tiers.reduce((n,t)=>n+t.remaining,0)}개 재고</b></div><Progress value={(b.totalTickets-b.remainingTickets)/b.totalTickets*100}/><Button variant="ghost" onClick={()=>toast.success("상품 구성을 불러왔습니다.")}>구성 관리</Button></article>)}</div></Card></>}
export function Reports(){const lab=useLab(),data=stores.map(s=>({name:s.shortName.replace("점",""),value:s.todaySales}));return <><PageHeader title="정산 리포트" description="지점별 매출과 운영 지표를 비교하고 내보냅니다." actions={<Button variant="ghost" onClick={()=>downloadCsv("store-report.csv",stores)}><Download size={16}/>리포트 다운로드</Button>}/><div className="two-col"><Card><SectionTitle title="지점별 오늘 매출"/><SimpleBarChart data={data}/></Card><Card><SectionTitle title="쿠지판 상태 비율"/><DonutChart data={["진행 중","예정","종료"].map((name,i)=>({name,value:lab.boards.filter(b=>b.status===name).length,color:["#7048e8","#20c997","#94a3b8"][i]}))}/></Card></div><Card><SectionTitle title="최근 7일 운영 추이"/><div className="report-table">{salesTrend.map(x=><div key={x.label}><b>{x.label}</b><Progress value={x.sales/22000}/><span>{won(x.sales)} · {x.tickets}장</span></div>)}</div></Card></>}
export function Notifications(){const lab=useLab(),[message,setMessage]=useState("");return <><PageHeader title="알림·메시지" description="운영 알림을 확인하고 지점 공지를 발송합니다." actions={<Button variant="ghost" onClick={lab.markAllRead}><CheckCircle2 size={16}/>모두 읽음</Button>}/><div className="two-col"><Card><SectionTitle title="운영 알림" sub={lab.notifications.filter(n=>!n.read).length+"개 읽지 않음"}/><div className="notification-list">{lab.notifications.map(n=><article key={n.id} className={n.read?"read":""}><span><Bell/></span><div><b>{n.title}</b><p>{n.message}</p><small>{n.createdAt}</small></div>{!n.read&&<i/>}</article>)}</div></Card><Card><SectionTitle title="지점 공지 발송" sub="선택한 지점 직원에게 전달됩니다."/><div className="message-compose"><MessageSquare/><label>공지 내용<textarea value={message} onChange={e=>setMessage(e.target.value)} placeholder="운영 공지를 입력하세요."/></label><Button disabled={!message.trim()} onClick={()=>{toast.success("공지를 발송했습니다.");setMessage("")}}><Send size={16}/>공지 발송</Button></div></Card></div></>}
export function SettingsPage(){const lab=useLab(),[saved,setSaved]=useState(false);return <><PageHeader title="연구소 설정" description="운영 기본값과 데모 환경을 관리합니다."/><div className="settings-grid"><Card><SectionTitle title="기본 운영 설정"/><div className="setting-list"><label>기본 수수료율<input type="number" defaultValue="3.5" step=".1"/>%</label><label>배송 마감 시간<input type="time" defaultValue="16:00"/></label><label>재고 경고 기준<input type="number" defaultValue="10"/>장</label><label className="switch-row">실시간 데모 데이터<span><input type="checkbox" checked={lab.demoLive} onChange={e=>lab.setDemoLive(e.target.checked)}/></span></label></div><Button onClick={()=>{setSaved(true);toast.success("설정을 저장했습니다.")}}><Save size={16}/>{saved?"저장 완료":"설정 저장"}</Button></Card><Card><SectionTitle title="연동 상태"/><div className="integration-card"><RefreshCw/><b>쿠지 프로그램 API</b><Badge tone="green">정상</Badge><p>마지막 동기화: 방금 전</p><code>/api/integrations/health</code></div><div className="integration-card"><Settings/><b>Firebase 데이터 모드</b><Badge tone="gray">데모</Badge><p>환경 변수를 설정하면 실데이터 모드로 전환됩니다.</p></div></Card></div></>}
