"use client";
import { X } from "lucide-react";import { cn } from "@/lib/utils";import { useEffect } from "react";
export function Card({children,className=""}:{children:React.ReactNode;className?:string}){return <section className={cn("lab-card",className)}>{children}</section>}
export function Button({children,className="",variant="primary",...props}:React.ButtonHTMLAttributes<HTMLButtonElement>&{variant?:"primary"|"secondary"|"danger"|"ghost"}){return <button className={cn("lab-button",variant,className)} {...props}>{children}</button>}
export function Badge({children,tone="purple"}:{children:React.ReactNode;tone?:"purple"|"green"|"amber"|"orange"|"red"|"blue"|"gray"}){return <span className={cn("badge","badge-"+tone)}>{children}</span>}
export function Progress({value,color="purple"}:{value:number;color?:string}){return <div className="progress-track" aria-label={"진행률 "+Math.round(value)+"%"}><span style={{width:Math.min(100,Math.max(0,value))+"%",background:color==="purple"?"linear-gradient(90deg,#6d3df5,#9f7aea)":color}} /></div>}
export function Modal({open,onClose,title,children,wide=false}:{open:boolean;onClose:()=>void;title:string;children:React.ReactNode;wide?:boolean}){useEffect(()=>{if(!open)return;const h=(e:KeyboardEvent)=>e.key==="Escape"&&onClose();document.addEventListener("keydown",h);return()=>document.removeEventListener("keydown",h)},[open,onClose]);if(!open)return null;return <div className="overlay" role="presentation" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><div className={cn("modal",wide&&"modal-wide")} role="dialog" aria-modal="true" aria-labelledby="modal-title"><div className="modal-head"><h2 id="modal-title">{title}</h2><button aria-label="닫기" onClick={onClose}><X size={18}/></button></div>{children}</div></div>}
export function Drawer({open,onClose,title,children}:{open:boolean;onClose:()=>void;title:string;children:React.ReactNode}){if(!open)return null;return <div className="overlay drawer-overlay" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><aside className="drawer" role="dialog" aria-modal="true"><div className="modal-head"><h2>{title}</h2><button aria-label="닫기" onClick={onClose}><X size={18}/></button></div>{children}</aside></div>}
export function EmptyState({title,body}:{title:string;body:string}){return <div className="empty-state"><div>🔬</div><strong>{title}</strong><p>{body}</p></div>}
